version: "3"
services:
  api:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15-alpine
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
      - .:/home
    ports:
      - 5432:5432
    environment:
      - .env

volumes:
  db_postgres_data:
